apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-eks-deployment
  labels:
    app: github-eks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-eks-deployment
  template:
    metadata:
      labels:
        app: github-eks-deployment
    spec:
      containers:
        - name: github-eks-deployment
          image: 454042841093.dkr.ecr.ap-south-1.amazonaws.com/github-eks-deployment:1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
