apiVersion: v1
kind: Service
metadata:
  name: github-eks-deployment
spec:
  selector:
    app: github-eks-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
